[Icon Theme]
Name=Breeze
Comment=Breeze by the KDE VDG, with SonicDE branding
Inherits=silver,hicolor
FollowsColorScheme=true
Directories=preferences/22,preferences/32,places/32,places/48,places/64,places/96

[preferences/22]
Size=22
Context=Applications
Type=Fixed

[preferences/32]
Size=32
Context=Applications
Type=Scalable
MinSize=32
MaxSize=256

[places/32]
Size=32
Context=Places
Type=Fixed

[places/48]
Size=48
Context=Places
Type=Fixed

[places/64]
Size=64
Context=Places
Type=Fixed

[places/96]
Size=96
Context=Places
Type=Scalable
MinSize=96
MaxSize=256
