install(DIRECTORY breeze/
        DESTINATION ${KDE_INSTALL_DATADIR}/plasma/desktoptheme/breeze)
install(DIRECTORY breeze-light/
        DESTINATION ${KDE_INSTALL_DATADIR}/plasma/desktoptheme/breeze-light)
install(DIRECTORY breeze-dark/
        DESTINATION ${KDE_INSTALL_DATADIR}/plasma/desktoptheme/breeze-dark)
